# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '2.13.1.dev3+g1a73881.d20230731'
__version_tuple__ = version_tuple = (2, 13, 1, 'dev3', 'g1a73881.d20230731')
